package messaging

const (
	DELIVERER_TASK      = "DELIVERER_TASK"
	MONITOR_WORKFLOW    = "MONITOR_WORKFLOW"
	INFOMATION          = "INFOMATION"
	REQUEST_WORKER_SYNC = "REQUEST_WORKER_SYNC"
	CLIENT_STATUS       = "CLIENT_STATUS"
	REMOVE_CHANNEL      = "REMOVE_CHANNEL"
	RUNNER_HTTP         = "RUNNER_HTTP"
)
