POST http://localhost:8001/apis/v1/auth/login
Content-Type: application/json

{
    "username": "nghiabadao",
    "password": "pwd"
}

###

GET http://kairos.badaosuotdoi.com/apis/v1/login?name=client3&api_key=ca399d0d-2ef2-41f0-994a-5f3f563c93e5&secret_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjbGllbnRfaWQiOiIxIiwidXNlcl9pZCI6IjEiLCJ1c2VyX3R5cGUiOiIyIn0.HTwiFg-FhRf9zBsQeoEScu0JONH5j3JVzNhgLHZy0RY
Content-Type: application/json

###

POST http://localhost:8001/apis/v1/auth/register
Content-Type: application/json

{
    "username": "nghiabadao",
    "password": "pwd",
    "repassword": "pwd"
}

###
POST http://localhost:8080/v1/tasks
Content-Type: application/json

{
  "id": "2",
  "name": "task2",
  "schedule": "@every 2s",
  "timezone": "Europe/Berlin",
  "metadata": {
    "user": "12345"
  },
  "executor": "http",
  "executor_config": {
      "method": "GET",
      "url": "http://example.com",
      "headers": "[]",
      "body": "",
      "timeout": "30",
      "expectCode": "200",
      "expectBody": "",
      "debug": "true"
  }
} 
###
POST http://localhost:8080/v1/tasks
Content-Type: application/json

{
  "id": "2",
  "name": "task2",
  "schedule": "@every 2s",
  "timezone": "Europe/Berlin",
  "tags": {
    "server": "true:1"
  },
  "metadata": {
    "user": "12345"
  },
  "executor": "nats",
  "executor_config": {
    "url": "nats://127.0.0.1:4222", 
    "message": "the message",
    "subject": "hello",
    "userName":"",
    "password":""
  }
} 
###
POST http://localhost:8080/v1/tasks
Content-Type: application/json

{
  "id": "2",
  "name": "task2",
  "timezone": "Europe/Berlin",
  "tags": {
    "server": "true:1"
  },
  "metadata": {
    "user": "12345"
  },
  "executor": "file",
  "executor_config": {
    "path": "./main.go",
    "method": "read"
  }
} 

###Users/nghiabadao/Code/project/backend_cms
POST http://localhost:8082/v1/tasks
Content-Type: application/json

{
  "id": "2",
  "name": "task2",
  "timezone": "Europe/Berlin",
  "tags": {
    "server": "true:1"
  },
  "metadata": {
    "user": "12345"
  },
  "executor": "script",
  "executor_config":  {
    "command": "/bin/sh",
    "commandArgs": "[\"-c\", \"cd /Users/nghiabadao/Code/demo/shopok && git pull  \"]"
  }
} 

###

POST http://localhost:8080/v1/tasks
Content-Type: application/json

{
  "id": "2",
  "name": "task2",
  "timezone": "Europe/Berlin",
  "tags": {
    "server": "true:1"
  },
  "metadata": {
    "user": "12345"
  },
  "executor": "dockerlite",
  "executor_config":  {
    "action":"build",
    "imageName": "nexta2020/shopok",
    "contextDir": "/Users/nghiabadao/Code/demo/shopok"
  }
} 


###
POST http://localhost:8080/v1/tasks
Content-Type: application/json

{
  "id": "2",
  "name": "task2",
  "timezone": "Europe/Berlin",
  "tags": {
    "server": "true:1"
  },
  "executor": "k8sdeploy",
  "executor_config": {
    "service": "shopok",
    "cmd": "deploy",
    "namespace": "demo"
  }
} 

###
POST http://localhost:8080/v1/tasks
Content-Type: application/json

{
  "id": "2",
  "name": "task2",
  "timezone": "Europe/Berlin",
  "tags": {
    "server": "true:1"
  },
  "executor": "k8sdeploy",
  "executor_config": {
    "service": "shopok",
    "cmd": "log",
    "namespace": "demo"
  }
} 


###
POST http://localhost:8080/v1/tasks
Content-Type: application/json

{
  "id": "2",
  "name": "task2",
  "timezone": "Europe/Berlin",
  "tags": {
    "server": "true:1"
  },
  "metadata": {
    "user": "12345"
  },
  "executor": "sql",
  "executor_config": {
    "driver": "mysql",
    "host": "localhost",
    "port": "3306",
    "user": "nghia",
    "password": "root",
    "dbname": "workflow",
    "instance": "multi"
  }
} 

###
POST http://localhost:8080/v1/tasks
Content-Type: application/json

{
  "id": "2",
  "name": "task2",
  "timezone": "Europe/Berlin",
  "tags": {
    "server": "true:1"
  },
  "metadata": {
    "user": "12345"
  },
  "executor": "sql",
  "executor_config": {
    "driver": "mysql",
    "host": "localhost",
    "port": "3306",
    "user": "nghia",
    "password": "root",
    "dbname": "workflow",
    "sql": "select * from users limit 2",
    "instance": "multi"
  }
} 
###
###
POST http://localhost:8080/v1/tasks
Content-Type: application/json

{
  "id": "3",
  "name": "postgres",
  "timezone": "Europe/Berlin",
  "tags": {
    "server": "true:1"
  },
  "metadata": {
    "user": "12345"
  },
  "executor": "sql",
  "executor_config": {
   "driver": "postgres",
    "host": "localhost",
    "port": "5432",
    "user": "kairos",
    "password": "kairos",
    "dbname": "kairos",
    "otherConfig": "sslmode = disable",
    "sql": "select * from users"
  }
} 

###
POST http://localhost:8080/v1/tasks
Content-Type: application/json

{
  "id": "3",
  "name": "node",
  "timezone": "Europe/Berlin",
  "tags": {
    "server": "true:1"
  },
  "metadata": {
    "user": "12345"
  },
  "executor": "node",
  "executor_config": {
    "test": "abc"
  }
} 
###

DELETE http://localhost:8080/v1/plugin/node/delete
Content-Type: application/json


###
POST http://localhost:8080/v1/tasks/list
Content-Type: application/json

{
 
}

###
GET http://localhost:8080/v1/workflow/68/detail
Content-Type: application/json

###
DELETE http://localhost:8080/v1/task/327/delete
Content-Type: application/json
###
DELETE http://localhost:8080/v1/broker/306/delete
Content-Type: application/json

###
DELETE http://localhost:8080/v1/workflow/34/delete
Content-Type: application/json
###
GET http://localhost:8090
###
POST http://localhost:8080/v1/runtask
Content-Type: application/json

{
  "task": {
    "id": 95,
    "workflow_id": 61,
    "input": "{\"method\":\"read\",\"path\":\"/text.txt\"}"
  }
}

###
POST http://localhost:8080/v1/runtask
Content-Type: application/json

{
  "task": {
    "id": 34,
    "workflow_id": 31,
    "input": "{\"sql\":\"select * from users where  id =2 \"}"
  }
}
###
POST http://localhost:8080/v1/broker/record
Content-Type: application/json

{
  "broker_id": 44
}
###
POST http://localhost:8080/v1/queue
Content-Type: application/json

{
  "k":"100",
  "v": "xyz4"
}

###
GET http://localhost:8080/v1/user_sql-119/queue
Content-Type: application/json

###
GET http://localhost:8080/v1/293/task
Content-Type: application/json

 
###
DELETE http://localhost:8081/v1/task/295/delete
Content-Type: application/json

###
GET http://localhost:8080/v1/view/2/executions

###
GET http://localhost:3111/apis/login
###
POST http://localhost:3111/apis/apply-collection
Content-Type: application/json
###
GET http://badaosuotdoi.com/apis/v1/service/workflow/list
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2Nlc3NfdXVpZCI6IjRjZjIwMzY2LThjMjYtNDY0MS05NzI3LTc5YTBkNDUyYmY3YSIsImV4cCI6MTcwMTg1MjYyNCwidXNlcl9pZCI6IjEiLCJ1c2VyX25hbWUiOiJtaW5obmdoaWFiYWRhbzEwMDJAZ21haWwuY29tIn0.rNuSeu37JTQeppqKR1oaUyNsqXy2BrCom2cTR4o_dgw

###
DELETE http://localhost:8001/apis/v1/service/workflow/32/drop
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2Nlc3NfdXVpZCI6IjRjZjIwMzY2LThjMjYtNDY0MS05NzI3LTc5YTBkNDUyYmY3YSIsImV4cCI6MTcwMTg1MjYyNCwidXNlcl9pZCI6IjEiLCJ1c2VyX25hbWUiOiJtaW5obmdoaWFiYWRhbzEwMDJAZ21haWwuY29tIn0.rNuSeu37JTQeppqKR1oaUyNsqXy2BrCom2cTR4o_dgw

###
GET http://localhost:8001/apis/v1/service/workflow/3/detail
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2Nlc3NfdXVpZCI6IjRjZjIwMzY2LThjMjYtNDY0MS05NzI3LTc5YTBkNDUyYmY3YSIsImV4cCI6MTcwMTg1MjYyNCwidXNlcl9pZCI6IjEiLCJ1c2VyX25hbWUiOiJtaW5obmdoaWFiYWRhbzEwMDJAZ21haWwuY29tIn0.rNuSeu37JTQeppqKR1oaUyNsqXy2BrCom2cTR4o_dgw

###
GET http://localhost:8001/apis/v1/service/client/list
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2Nlc3NfdXVpZCI6IjRjZjIwMzY2LThjMjYtNDY0MS05NzI3LTc5YTBkNDUyYmY3YSIsImV4cCI6MTcwMTg1MjYyNCwidXNlcl9pZCI6IjEiLCJ1c2VyX25hbWUiOiJtaW5obmdoaWFiYWRhbzEwMDJAZ21haWwuY29tIn0.rNuSeu37JTQeppqKR1oaUyNsqXy2BrCom2cTR4o_dgw

###
GET http://localhost:8001/apis/v1/service/channel/list
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2Nlc3NfdXVpZCI6IjRjZjIwMzY2LThjMjYtNDY0MS05NzI3LTc5YTBkNDUyYmY3YSIsImV4cCI6MTcwMTg1MjYyNCwidXNlcl9pZCI6IjEiLCJ1c2VyX25hbWUiOiJtaW5obmdoaWFiYWRhbzEwMDJAZ21haWwuY29tIn0.rNuSeu37JTQeppqKR1oaUyNsqXy2BrCom2cTR4o_dgw

###
POST http://localhost:8001/apis/v1/service/channel/create
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjbGllbnRfaWQiOiIwIiwidXNlcl9pZCI6IjEiLCJ1c2VyX3R5cGUiOiIwIn0.qSvwg2tjV0v050_2i4XZwybDv2aNjmYl0S84MdBzgU8

{
  "name": "abc"
}
###
GET http://kairos.badaosuotdoi.com/apis/v1/service/user/info
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjbGllbnRfaWQiOiI2IiwidXNlcl9pZCI6IjEiLCJ1c2VyX3R5cGUiOiIyIn0.1xkyz267_8y3zdnPAV-D_OuF_9V-lZJW_MLm0tyFz4I

###
POST http://localhost:8001/apis/v1/service/certificate/create
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjbGllbnRfaWQiOiIwIiwidXNlcl9pZCI6IjEiLCJ1c2VyX3R5cGUiOiIwIn0.qSvwg2tjV0v050_2i4XZwybDv2aNjmYl0S84MdBzgU8

{
  "name":"hello",
  "channel_permissions": [
  {
    "channel_id": 1,
    "role": 3
  }
]
}

###
GET http://localhost:8001/apis/v1/service/certificate/list
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjbGllbnRfaWQiOiIwIiwidXNlcl9pZCI6IjEiLCJ1c2VyX3R5cGUiOiIwIn0.qSvwg2tjV0v050_2i4XZwybDv2aNjmYl0S84MdBzgU8

###
GET http://localhost:8001/apis/v1/service/certificate/permit
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjbGllbnRfaWQiOiIxIiwidXNlcl9pZCI6IjEiLCJ1c2VyX3R5cGUiOiIyIn0.HTwiFg-FhRf9zBsQeoEScu0JONH5j3JVzNhgLHZy0RY
api-key: 6e679f0a-7ce1-4d9f-a00a-c8ecc086ba57

###
POST http://localhost:8001/apis/v1/service/workflow/request/sync
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjbGllbnRfaWQiOiIzIiwidXNlcl9pZCI6IjEiLCJ1c2VyX3R5cGUiOiIyIn0.bNVPBs5VyXjqaR_khv_HleDa2zAOB_BCduDLuxhjwmI
api-key: 5f996c81-5677-4d25-b30e-650724f14499

{
  "cmd": 4,
  "run_on": "listen_channel",
  "content":{
    "msg":{
      "sql": "select * from users limit 1"
    }
  }
}

###
POST http://localhost:8001/apis/v1/service/functions/create
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjbGllbnRfaWQiOiI2IiwidXNlcl9pZCI6IjEiLCJ1c2VyX3R5cGUiOiIyIn0.1xkyz267_8y3zdnPAV-D_OuF_9V-lZJW_MLm0tyFz4I

{
  "content": "function hello(){return \"hello\"}",
  "name":"hello"
}


###
GET http://localhost:8001/apis/v1/service/functions/list
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjbGllbnRfaWQiOiI2IiwidXNlcl9pZCI6IjEiLCJ1c2VyX3R5cGUiOiIyIn0.1xkyz267_8y3zdnPAV-D_OuF_9V-lZJW_MLm0tyFz4I

###
POST http://localhost:8001/apis/v1/service/graph/get
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjbGllbnRfaWQiOiI2IiwidXNlcl9pZCI6IjEiLCJ1c2VyX3R5cGUiOiIyIn0.1xkyz267_8y3zdnPAV-D_OuF_9V-lZJW_MLm0tyFz4I

{
  "workflow_ids": [22,23]
}

###
POST http://localhost:8001/apis/v1/service/graph/data
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjbGllbnRfaWQiOiI2IiwidXNlcl9pZCI6IjEiLCJ1c2VyX3R5cGUiOiIyIn0.1xkyz267_8y3zdnPAV-D_OuF_9V-lZJW_MLm0tyFz4I

{
  "workflow_ids": [22,23]
}
###

GET http://localhost:8001/apis/v1/service/record/client/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjbGllbnRfaWQiOiI2IiwidXNlcl9pZCI6IjEiLCJ1c2VyX3R5cGUiOiIyIn0.1xkyz267_8y3zdnPAV-D_OuF_9V-lZJW_MLm0tyFz4I

###
POST http://localhost:8001/apis/v1/service/record/message_flows
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjbGllbnRfaWQiOiI2IiwidXNlcl9pZCI6IjEiLCJ1c2VyX3R5cGUiOiIyIn0.1xkyz267_8y3zdnPAV-D_OuF_9V-lZJW_MLm0tyFz4I

{
  
}

###
GET http://localhost:8001/apis/v1/service/graph/timeline
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjbGllbnRfaWQiOiI2IiwidXNlcl9pZCI6IjEiLCJ1c2VyX3R5cGUiOiIyIn0.1xkyz267_8y3zdnPAV-D_OuF_9V-lZJW_MLm0tyFz4I

###
GET http://localhost:8001/apis/v1/service/graph/group?group=kairos-200-1703325003
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjbGllbnRfaWQiOiI2IiwidXNlcl9pZCI6IjEiLCJ1c2VyX3R5cGUiOiIyIn0.1xkyz267_8y3zdnPAV-D_OuF_9V-lZJW_MLm0tyFz4I

###
POST http://kairos.badaosuotdoi.com/apis/v1/service/graph/part
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjbGllbnRfaWQiOiI2IiwidXNlcl9pZCI6IjEiLCJ1c2VyX3R5cGUiOiIyIn0.1xkyz267_8y3zdnPAV-D_OuF_9V-lZJW_MLm0tyFz4I

{
  "parts": ["part-201-1703353905"],
  "parents": ["part-201-1703353905"]
}

###
