POST http://localhost:8001/apis/v1/auth/login
Content-Type: application/json

{
    "username": "nghiabadao",
    "password": "pwd"
}

###

POST http://localhost:8001/apis/v1/auth/register
Content-Type: application/json

{
    "username": "nghiabadao",
    "password": "pwd",
    "repassword": "pwd"
}
