POST http://localhost:8001/apis/v1/auth/login
Content-Type: application/json

{
    "username": "nghiabadao",
    "password": "pwd"
}

###
GET http://localhost:8001/apis/v1/login
Content-Type: application/json

###

POST http://localhost:8001/apis/v1/auth/register
Content-Type: application/json

{
    "username": "nghiabadao",
    "password": "pwd",
    "repassword": "pwd"
}

###
POST http://localhost:8080/v1/tasks
Content-Type: application/json

{
  "id": "2",
  "name": "task2",
  "schedule": "@every 2s",
  "timezone": "Europe/Berlin",
  "metadata": {
    "user": "12345"
  },
  "executor": "http",
  "executor_config": {
      "method": "GET",
      "url": "http://example.com",
      "headers": "[]",
      "body": "",
      "timeout": "30",
      "expectCode": "200",
      "expectBody": "",
      "debug": "true"
  }
} 
###
POST http://localhost:8080/v1/tasks
Content-Type: application/json

{
  "id": "2",
  "name": "task2",
  "schedule": "@every 2s",
  "timezone": "Europe/Berlin",
  "disabled": false,
  "tags": {
    "server": "true:1"
  },
  "metadata": {
    "user": "12345"
  },
  "executor": "nats",
  "executor_config": {
    "url": "nats://127.0.0.1:4222", 
    "message": "the message",
    "subject": "hello",
    "userName":"",
    "password":""
  }
} 
###
POST http://localhost:8080/v1/tasks
Content-Type: application/json

{
  "id": "2",
  "name": "task2",
  "schedule": "@every 2s",
  "timezone": "Europe/Berlin",
  "disabled": false,
  "tags": {
    "server": "true:1"
  },
  "metadata": {
    "user": "12345"
  },
  "executor": "file",
  "executor_config": {
    "path": "./main.go"
  }
} 
###
POST http://localhost:8080/v1/queue
Content-Type: application/json

{
  "task_id": "1",
  "k":"xyz4",
  "v": "abc4"
}

###
GET http://localhost:8082/v1/110/queue
Content-Type: application/json

###
GET http://localhost:8080/v1/tasks
Content-Type: application/json
###
GET http://localhost:8080/v1/293/task
Content-Type: application/json

###
DELETE http://localhost:8080/v1/2/delete
Content-Type: application/json
 
###
DELETE http://localhost:8081/v1/295/delete
Content-Type: application/json



###
GET http://localhost:8080/v1/view/335/executions

###
GET http://localhost:3111/apis/login
###
POST http://localhost:3111/apis/apply-collection
Content-Type: application/json
###
GET http://localhost:8001/apis/v1/service/workflow/list
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2Nlc3NfdXVpZCI6IjRjZjIwMzY2LThjMjYtNDY0MS05NzI3LTc5YTBkNDUyYmY3YSIsImV4cCI6MTcwMTg1MjYyNCwidXNlcl9pZCI6IjEiLCJ1c2VyX25hbWUiOiJtaW5obmdoaWFiYWRhbzEwMDJAZ21haWwuY29tIn0.rNuSeu37JTQeppqKR1oaUyNsqXy2BrCom2cTR4o_dgw

###
DELETE http://localhost:8001/apis/v1/service/workflow/32/drop
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2Nlc3NfdXVpZCI6IjRjZjIwMzY2LThjMjYtNDY0MS05NzI3LTc5YTBkNDUyYmY3YSIsImV4cCI6MTcwMTg1MjYyNCwidXNlcl9pZCI6IjEiLCJ1c2VyX25hbWUiOiJtaW5obmdoaWFiYWRhbzEwMDJAZ21haWwuY29tIn0.rNuSeu37JTQeppqKR1oaUyNsqXy2BrCom2cTR4o_dgw

###
GET http://localhost:8001/apis/v1/service/workflow/3/detail
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2Nlc3NfdXVpZCI6IjRjZjIwMzY2LThjMjYtNDY0MS05NzI3LTc5YTBkNDUyYmY3YSIsImV4cCI6MTcwMTg1MjYyNCwidXNlcl9pZCI6IjEiLCJ1c2VyX25hbWUiOiJtaW5obmdoaWFiYWRhbzEwMDJAZ21haWwuY29tIn0.rNuSeu37JTQeppqKR1oaUyNsqXy2BrCom2cTR4o_dgw

###
GET http://localhost:8001/apis/v1/service/client/list
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2Nlc3NfdXVpZCI6IjRjZjIwMzY2LThjMjYtNDY0MS05NzI3LTc5YTBkNDUyYmY3YSIsImV4cCI6MTcwMTg1MjYyNCwidXNlcl9pZCI6IjEiLCJ1c2VyX25hbWUiOiJtaW5obmdoaWFiYWRhbzEwMDJAZ21haWwuY29tIn0.rNuSeu37JTQeppqKR1oaUyNsqXy2BrCom2cTR4o_dgw

###
GET http://localhost:8001/apis/v1/service/channel/list
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2Nlc3NfdXVpZCI6IjRjZjIwMzY2LThjMjYtNDY0MS05NzI3LTc5YTBkNDUyYmY3YSIsImV4cCI6MTcwMTg1MjYyNCwidXNlcl9pZCI6IjEiLCJ1c2VyX25hbWUiOiJtaW5obmdoaWFiYWRhbzEwMDJAZ21haWwuY29tIn0.rNuSeu37JTQeppqKR1oaUyNsqXy2BrCom2cTR4o_dgw

###
POST http://localhost:8001/apis/v1/service/channel/create
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjbGllbnRfaWQiOiIwIiwidXNlcl9pZCI6IjEiLCJ1c2VyX3R5cGUiOiIwIn0.qSvwg2tjV0v050_2i4XZwybDv2aNjmYl0S84MdBzgU8

{
  "name": "abc"
}
###
GET http://localhost:8001/apis/v1/service/user/info
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2Nlc3NfdXVpZCI6IjRjZjIwMzY2LThjMjYtNDY0MS05NzI3LTc5YTBkNDUyYmY3YSIsImV4cCI6MTcwMTg1MjYyNCwidXNlcl9pZCI6IjEiLCJ1c2VyX25hbWUiOiJtaW5obmdoaWFiYWRhbzEwMDJAZ21haWwuY29tIn0.rNuSeu37JTQeppqKR1oaUyNsqXy2BrCom2cTR4o_dgw

###
POST http://localhost:8001/apis/v1/service/certificate/create
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjbGllbnRfaWQiOiIwIiwidXNlcl9pZCI6IjEiLCJ1c2VyX3R5cGUiOiIwIn0.qSvwg2tjV0v050_2i4XZwybDv2aNjmYl0S84MdBzgU8

[
  {
    "channel_id": 1,
    "role": 1
  }
]

###
GET http://localhost:8001/apis/v1/service/certificate/list
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjbGllbnRfaWQiOiIwIiwidXNlcl9pZCI6IjEiLCJ1c2VyX3R5cGUiOiIwIn0.qSvwg2tjV0v050_2i4XZwybDv2aNjmYl0S84MdBzgU8
