version: '1'
name: debug
vars:
tasks:
  sql:
    executor: sql
    clients: [client1]
    wait: input
    payload: |
      {
        "driver": "mysql",
        "host": "127.0.0.1",
        "port": "3306",
        "user": "nghia",
        "password": "root",
        "dbname": "workflow"
      }

brokers:
  brok:
    listens: [listen_channel]
    flows: |
      {{get .listen_channel ("content") | get ("msg") | .msg }}
          {{define .req map | put ("sql") .msg | .req }}
              {{sendsync .req  .sql_task | .result }}
              {{send .result .listen_channel}}
          {{end}}
      {{end}}