apiVersion: apps/v1
kind: Deployment
metadata:
  name: runner
  namespace: kairos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: runner
  template:
    metadata:
      labels:
        app: runner
    spec:
      containers:
        - name: runner
          image: nexta2020/kairos
          ports:
            - containerPort: 8005
          command:
            - "kairos"
            - "runner"
            - "--file"
            - "/config/runner.yaml"
          volumeMounts:
            - name: config-volume
              mountPath: /config
      volumes:
        - name: config-volume
          configMap:
            name: runner-config
---
apiVersion: v1
kind: Service
metadata:
  namespace: kairos
  name: runner
spec:
  selector:
    app: runner
  ports:
    - name: port-8005
      port: 8005
      targetPort: 8005
      protocol: TCP
