runner:
  port: 8005
  max_workflow_concurrent: 10000
  max_attemp_deliver: 100
  timeout_retry_deliver: 10
  deliver_timeout: 3

nats:
  url: nats://nats.kairos.svc.cluster.local
  name: runner
  reconnect_wait: 2
  max_reconnect: 10

db: 
  postgres:
    username: kairos
    password: kairos
    uri: 61.28.230.61
    port: 5432
    databaseName: kairos
    protocol: tcp