serverPort: 3111
httpEndpoint: "http://nghia.nexta.vn"
serverPubSubEnpoint: "ws://nghia.nexta.vn/server/pubsub"
pubSubEnpoint: "ws://nghia.nexta.vn/pubsub"
nodeName: "kairosdeamon"
agentHTTPAddrPort: 8080
agentDefaultPort: 6868
agentDataDir: "kairos.boltdb"