serverPort: 3111
loginEndpoint: "http://kairos.badaosuotdoi.com/apis/v1/login"
serverPubSubEnpoint: "ws://kairos.badaosuotdoi.com/server/pubsub"
pubSubEnpoint: "ws://kairos.badaosuotdoi.com/pubsub"
nodeName: "kairosdeamon"
agentHTTPAddrPort: 8080
agentDefaultPort: 6868
agentDataDir: "kairos.boltdb"