workflows:
  - key: root
    trigger_time: * * * 0 0 1
    retries: 3
    tasks:
      - key: taks1
        trigger_time: * 0 * 0 1
        executor: git
        timeout: 3s
        retries: 2
        inputs:
          - aa:bb
          - cc:dd
        run: git clone abc
      - key: taks2
        dependencies: [taks1]
        trigger_time: * 0 * 0 2
        executor: docker
        timeout: 4s
        retries: 2
        inputs:
          - abc:fff
          - hhh:ccc
        run: xyz
    
        

