apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpserver
  namespace: kairos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kairos
  template:
    metadata:
      labels:
        app: kairos
    spec:
      containers:
        - name: httpserver
          image: nexta2020/kairos
          ports:
            - containerPort: 8003
          command:
            - "kairos"
            - "deliverer"
            - "--file"
            - "deliverer.yaml"