apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpserver
  namespace: kairos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kairos
  template:
    metadata:
      labels:
        app: kairos
    spec:
      containers:
        - name: httpserver
          image: nexta2020/kairos
          ports:
            - containerPort: 8001
            - containerPort: 8002
          command:
            - "kairos"
            - "httpserver"
            - "--file"
            - "/config/httpserver.yaml"
          volumeMounts:
            - name: config-volume
              mountPath: /config
      volumes:
        - name: config-volume
          configMap:
            name: httpserver-config

---
apiVersion: v1
kind: Service
metadata:
  namespace: kairos
  name: httpserver
spec:
  selector:
    app: httpserver
  ports:
    - name: port-8001
      port: 8001
      targetPort: 8001
      protocol: TCP
    - name: port-8002
      port: 8002
      targetPort: 8002
      protocol: TCP

