apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpserver
  namespace: kairos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: httpserver
  template:
    metadata:
      labels:
        app: httpserver
    spec:
      containers:
        - name: httpserver
          image: nexta2020/kairos
          ports:
            - containerPort: 8001
            - containerPort: 8002
          command:
            - "kairos"
            - "httpserver"
            - "--file"
            - "/config/httpserver.yaml"
          volumeMounts:
            - name: config-volume
              mountPath: /config
      volumes:
        - name: config-volume
          configMap:
            name: httpserver-config

---
apiVersion: v1
kind: Service
metadata:
  namespace: kairos
  name: httpserver
spec:
  selector:
    app: httpserver
  ports:
    - name: port-8001
      port: 8001
      targetPort: 8001
      protocol: TCP
    - name: port-8002
      port: 8002
      targetPort: 8002
      protocol: TCP
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  namespace: kairos
  name: kairos
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/proxy-body-size: "1000m"
spec:
  rules:
    - host: badaosuotdoi.com
      http:
        paths:
          - path: /apis/v1/
            backend:
              serviceName: httpserver
              servicePort: port-8001
          - path: /server/
            backend:
              serviceName: httpserver
              servicePort: port-8002