collection:
  namespace: abcd
  workflows:
    - key: root
      tasks:
        - key: task1
          schedule: "* 0 * 0 1"
          timezone: "HN"
          executor: lo
          timeout: 3s
          retries: 2
          inputs:
            vars: {{.ABC}}
          outputs:
            dir: 
          env_exec: local
          run: 
        - key: task2 
          deps: [task1]
          schedule: "* 0 * 0 2"
          executor: docker
          timeout: 4s
          retries: 2
          strict: true
          env_exec: kairos
          inputs:
          run: once  
  
    
        

