collection:
  namespace: abcd
  workflows:
    - key: root
      tasks:
        - key: task1
          schedule: "* 0 * 0 1"
          timezone: "HN"
          executor: git
          timeout: 3s
          retries: 2
          inputs:
            - aa:bb
            - cc:dd
          env_exec: local
          run: git clone abc
        - key: task2 
          dependencies: [task1]
          schedule: "* 0 * 0 2"
          executor: docker
          timeout: 4s
          retries: 2
          strict: true
          env_exec: kairos
          inputs:
            - abc:fff
            - hhh:ccc
          run: xyz  

    - key: root2
      tasks:
        - key: task1
          schedule: "* 0 * 0 1"
          executor: git
          timeout: 3s
          retries: 2
          inputs:
            - aa:bb
            - cc:dd
          run: git clone abc
          env_exec: xyz
        - key: task2
          dependencies: [task1]
          schedule: "* 0 * 0 2"
          executor: docker
          timeout: 4s
          retries: 2
          inputs:
            - abc:fff
            - hhh:ccc
          run: xyz    
  
    
        

