apiVersion: apps/v1
kind: Deployment
metadata:
  name: deliverer
  namespace: kairos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deliverer
  template:
    metadata:
      labels:
        app: deliverer
    spec:
      containers:
        - name: deliverer
          image: nexta2020/kairos
          ports:
            - containerPort: 8003
          command:
            - "kairos"
            - "deliverer"
            - "--file"
            - "/config/deliverer.yaml"
          volumeMounts:
            - name: config-volume
              mountPath: /config
      volumes:
        - name: config-volume
          configMap:
            name: deliverer-config
---
apiVersion: v1
kind: Service
metadata:
  namespace: kairos
  name: deliverer
spec:
  selector:
    app: deliverer
  ports:
    - port: 8003
      targetPort: 8003
      protocol: TCP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: kairos
  name: deliverer
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    nginx.ingress.kubernetes.io/websocket-services: deliverer
    nginx.org/websocket-services: deliverer
spec:
  rules:
  - host: kairos.badaosuotdoi.com
    http:
      paths:
      - path: /pubsub
        pathType: Prefix
        backend:
          service:
            name: deliverer
            port:
              number: 8003

