apiVersion: apps/v1
kind: Deployment
metadata:
  name: deliverer
  namespace: kairos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kairos
  template:
    metadata:
      labels:
        app: kairos
    spec:
      containers:
        - name: deliverer
          image: nexta2020/kairos
          ports:
            - containerPort: 8003
          command:
            - "kairos"
            - "deliverer"
            - "--file"
            - "deliverer.yaml"
---
apiVersion: v1
kind: Service
metadata:
  namespace: kairos
  name: deliverer
spec:
  selector:
    app: deliverer
  ports:
    - port: 8003
      targetPort: 8003
      protocol: TCP

