apiVersion: apps/v1
kind: Deployment
metadata:
  name: deliverer
  namespace: kairos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kairos
  template:
    metadata:
      labels:
        app: kairos
    spec:
      containers:
        - name: deliverer
          image: nexta2020/kairos
          ports:
            - containerPort: 8001
            - containerPort: 8002
          command:
            - "kairos"
            - "httpserver"
            - "--file"
            - "httpserver.yaml"