
CREATE USER kairos WITH PASSWORD 'kairos';
ALTER USER kairos WITH SUPERUSER;
CREATE DATABASE kairos_db;
GRANT CONNECT ON DATABASE kairos_db TO kairos;
GRANT ALL PRIVILEGES ON DATABASE kairos_db TO kairos;
