version: '2'
services:
  webui:
    build: .
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_HTTPSERVER=http://kairos.badaosuotdoi.com
      - REACT_APP_BASE_URL=http://localhost:3000/
