version: '2'
services:
  webui:
    build: .
    ports:
      - "3456:3000"
    environment:
      - REACT_APP_HTTPSERVER=http://nghia.nexta.vn
      - REACT_APP_BASE_URL=http://kairosweb.badaosuotdoi.com
      - REACT_APP_WEBSOCKET=ws://nghia.nexta.vn
