DROP TABLE IF EXISTS clients;
DROP TABLE IF EXISTS message_flows;
DROP TABLE IF EXISTS task_records;
DROP TABLE IF EXISTS task_summary;
DROP TABLE IF EXISTS brokers;
DROP TABLE IF EXISTS vars;
DROP TABLE IF EXISTS tasks;
DROP TABLE IF EXISTS workflows;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS schema_migrations;

