// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.20.3
// source: proto/httpserver.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Command_Type int32

const (
	Command_ChannelPermitRequest Command_Type = 0
)

// Enum value maps for Command_Type.
var (
	Command_Type_name = map[int32]string{
		0: "ChannelPermitRequest",
	}
	Command_Type_value = map[string]int32{
		"ChannelPermitRequest": 0,
	}
)

func (x Command_Type) Enum() *Command_Type {
	p := new(Command_Type)
	*p = x
	return p
}

func (x Command_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Command_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_httpserver_proto_enumTypes[0].Descriptor()
}

func (Command_Type) Type() protoreflect.EnumType {
	return &file_proto_httpserver_proto_enumTypes[0]
}

func (x Command_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Command_Type.Descriptor instead.
func (Command_Type) EnumDescriptor() ([]byte, []int) {
	return file_proto_httpserver_proto_rawDescGZIP(), []int{0, 0}
}

type Command struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ChannlePremit *ChannelPermitRequest `protobuf:"bytes,1,opt,name=channlePremit,proto3" json:"channlePremit,omitempty"`
}

func (x *Command) Reset() {
	*x = Command{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_httpserver_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Command) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Command) ProtoMessage() {}

func (x *Command) ProtoReflect() protoreflect.Message {
	mi := &file_proto_httpserver_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Command.ProtoReflect.Descriptor instead.
func (*Command) Descriptor() ([]byte, []int) {
	return file_proto_httpserver_proto_rawDescGZIP(), []int{0}
}

func (x *Command) GetChannlePremit() *ChannelPermitRequest {
	if x != nil {
		return x.ChannlePremit
	}
	return nil
}

type ChannelPermitRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CertID int64 `protobuf:"varint,1,opt,name=certID,proto3" json:"certID,omitempty"`
}

func (x *ChannelPermitRequest) Reset() {
	*x = ChannelPermitRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_httpserver_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChannelPermitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChannelPermitRequest) ProtoMessage() {}

func (x *ChannelPermitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_httpserver_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChannelPermitRequest.ProtoReflect.Descriptor instead.
func (*ChannelPermitRequest) Descriptor() ([]byte, []int) {
	return file_proto_httpserver_proto_rawDescGZIP(), []int{1}
}

func (x *ChannelPermitRequest) GetCertID() int64 {
	if x != nil {
		return x.CertID
	}
	return 0
}

type CommandReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ChannlePremit *ChannelPermitReply `protobuf:"bytes,1,opt,name=channlePremit,proto3" json:"channlePremit,omitempty"`
}

func (x *CommandReply) Reset() {
	*x = CommandReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_httpserver_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CommandReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandReply) ProtoMessage() {}

func (x *CommandReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_httpserver_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandReply.ProtoReflect.Descriptor instead.
func (*CommandReply) Descriptor() ([]byte, []int) {
	return file_proto_httpserver_proto_rawDescGZIP(), []int{2}
}

func (x *CommandReply) GetChannlePremit() *ChannelPermitReply {
	if x != nil {
		return x.ChannlePremit
	}
	return nil
}

type ChannelPermitReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ChannelPermits []*ChannelPermit `protobuf:"bytes,1,rep,name=channelPermits,proto3" json:"channelPermits,omitempty"`
}

func (x *ChannelPermitReply) Reset() {
	*x = ChannelPermitReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_httpserver_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChannelPermitReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChannelPermitReply) ProtoMessage() {}

func (x *ChannelPermitReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_httpserver_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChannelPermitReply.ProtoReflect.Descriptor instead.
func (*ChannelPermitReply) Descriptor() ([]byte, []int) {
	return file_proto_httpserver_proto_rawDescGZIP(), []int{3}
}

func (x *ChannelPermitReply) GetChannelPermits() []*ChannelPermit {
	if x != nil {
		return x.ChannelPermits
	}
	return nil
}

type ChannelPermit struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ChannelID   int64  `protobuf:"varint,1,opt,name=channelID,proto3" json:"channelID,omitempty"`
	ChannelName string `protobuf:"bytes,2,opt,name=channelName,proto3" json:"channelName,omitempty"`
	Role        int32  `protobuf:"varint,3,opt,name=role,proto3" json:"role,omitempty"`
}

func (x *ChannelPermit) Reset() {
	*x = ChannelPermit{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_httpserver_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChannelPermit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChannelPermit) ProtoMessage() {}

func (x *ChannelPermit) ProtoReflect() protoreflect.Message {
	mi := &file_proto_httpserver_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChannelPermit.ProtoReflect.Descriptor instead.
func (*ChannelPermit) Descriptor() ([]byte, []int) {
	return file_proto_httpserver_proto_rawDescGZIP(), []int{4}
}

func (x *ChannelPermit) GetChannelID() int64 {
	if x != nil {
		return x.ChannelID
	}
	return 0
}

func (x *ChannelPermit) GetChannelName() string {
	if x != nil {
		return x.ChannelName
	}
	return ""
}

func (x *ChannelPermit) GetRole() int32 {
	if x != nil {
		return x.Role
	}
	return 0
}

var File_proto_httpserver_proto protoreflect.FileDescriptor

var file_proto_httpserver_proto_rawDesc = []byte{
	0x0a, 0x16, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x68, 0x74, 0x74, 0x70, 0x73, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0x6e, 0x0a, 0x07, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x12, 0x41, 0x0a, 0x0d, 0x63, 0x68,
	0x61, 0x6e, 0x6e, 0x6c, 0x65, 0x50, 0x72, 0x65, 0x6d, 0x69, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65,
	0x6c, 0x50, 0x65, 0x72, 0x6d, 0x69, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x0d,
	0x63, 0x68, 0x61, 0x6e, 0x6e, 0x6c, 0x65, 0x50, 0x72, 0x65, 0x6d, 0x69, 0x74, 0x22, 0x20, 0x0a,
	0x04, 0x54, 0x79, 0x70, 0x65, 0x12, 0x18, 0x0a, 0x14, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c,
	0x50, 0x65, 0x72, 0x6d, 0x69, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x10, 0x00, 0x22,
	0x2e, 0x0a, 0x14, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x50, 0x65, 0x72, 0x6d, 0x69, 0x74,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x63, 0x65, 0x72, 0x74, 0x49,
	0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x63, 0x65, 0x72, 0x74, 0x49, 0x44, 0x22,
	0x4f, 0x0a, 0x0c, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12,
	0x3f, 0x0a, 0x0d, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x6c, 0x65, 0x50, 0x72, 0x65, 0x6d, 0x69, 0x74,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x43,
	0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x50, 0x65, 0x72, 0x6d, 0x69, 0x74, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x52, 0x0d, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x6c, 0x65, 0x50, 0x72, 0x65, 0x6d, 0x69, 0x74,
	0x22, 0x52, 0x0a, 0x12, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x50, 0x65, 0x72, 0x6d, 0x69,
	0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x3c, 0x0a, 0x0e, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65,
	0x6c, 0x50, 0x65, 0x72, 0x6d, 0x69, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x50, 0x65,
	0x72, 0x6d, 0x69, 0x74, 0x52, 0x0e, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x50, 0x65, 0x72,
	0x6d, 0x69, 0x74, 0x73, 0x22, 0x63, 0x0a, 0x0d, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x50,
	0x65, 0x72, 0x6d, 0x69, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c,
	0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65,
	0x6c, 0x49, 0x44, 0x12, 0x20, 0x0a, 0x0b, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x4e, 0x61,
	0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65,
	0x6c, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x72, 0x6f, 0x6c, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x04, 0x72, 0x6f, 0x6c, 0x65, 0x42, 0x2f, 0x5a, 0x2d, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x54, 0x48, 0x50, 0x54, 0x55, 0x48, 0x41, 0x2f,
	0x6b, 0x61, 0x69, 0x72, 0x6f, 0x73, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x70, 0x6c,
	0x75, 0x67, 0x69, 0x6e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_proto_httpserver_proto_rawDescOnce sync.Once
	file_proto_httpserver_proto_rawDescData = file_proto_httpserver_proto_rawDesc
)

func file_proto_httpserver_proto_rawDescGZIP() []byte {
	file_proto_httpserver_proto_rawDescOnce.Do(func() {
		file_proto_httpserver_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_httpserver_proto_rawDescData)
	})
	return file_proto_httpserver_proto_rawDescData
}

var file_proto_httpserver_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_httpserver_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_httpserver_proto_goTypes = []interface{}{
	(Command_Type)(0),            // 0: proto.Command.Type
	(*Command)(nil),              // 1: proto.Command
	(*ChannelPermitRequest)(nil), // 2: proto.ChannelPermitRequest
	(*CommandReply)(nil),         // 3: proto.CommandReply
	(*ChannelPermitReply)(nil),   // 4: proto.ChannelPermitReply
	(*ChannelPermit)(nil),        // 5: proto.ChannelPermit
}
var file_proto_httpserver_proto_depIdxs = []int32{
	2, // 0: proto.Command.channlePremit:type_name -> proto.ChannelPermitRequest
	4, // 1: proto.CommandReply.channlePremit:type_name -> proto.ChannelPermitReply
	5, // 2: proto.ChannelPermitReply.channelPermits:type_name -> proto.ChannelPermit
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_httpserver_proto_init() }
func file_proto_httpserver_proto_init() {
	if File_proto_httpserver_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_httpserver_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Command); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_httpserver_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChannelPermitRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_httpserver_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CommandReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_httpserver_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChannelPermitReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_httpserver_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChannelPermit); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_httpserver_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_httpserver_proto_goTypes,
		DependencyIndexes: file_proto_httpserver_proto_depIdxs,
		EnumInfos:         file_proto_httpserver_proto_enumTypes,
		MessageInfos:      file_proto_httpserver_proto_msgTypes,
	}.Build()
	File_proto_httpserver_proto = out.File
	file_proto_httpserver_proto_rawDesc = nil
	file_proto_httpserver_proto_goTypes = nil
	file_proto_httpserver_proto_depIdxs = nil
}
